#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
AI Office Assistant — 初始化腳本

首次 clone 後執行，建立必要的目錄結構與模板檔案。
已存在的檔案不會被覆蓋。

使用方式：
    conda activate ai-office
    python init.py                         # 只裝 core
    python init.py --with ocr --with ml    # core + optional groups
    python init.py --with ai-runtime-gpu   # 啟用 GPU PyTorch
    python init.py --force-cpu             # 強制 CPU 模式（偵測不影響）
    python init.py --force-gpu             # 強制 GPU 模式
    python init.py --project <name>        # 同時建立一個新專案
"""

import argparse
import os
import platform
import shutil
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent


# ============================================================
# 0. 硬體偵測
# ============================================================

def detect_os_info():
    """偵測作業系統資訊，回傳 dict。"""
    return {
        "system": platform.system(),
        "release": platform.release(),
        "machine": platform.machine(),
        "is_windows": sys.platform == "win32",
        "is_linux": sys.platform.startswith("linux"),
        "is_macos": sys.platform == "darwin",
    }


def detect_gpu():
    """偵測 NVIDIA GPU，回傳 dict。無 GPU 時 gpu_available=False。"""
    result = {
        "gpu_available": False,
        "gpu_name": None,
        "vram_mb": None,
        "cuda_driver": None,
    }
    try:
        output = subprocess.check_output(
            ["nvidia-smi", "--query-gpu=name,memory.total,driver_version",
             "--format=csv,noheader,nounits"],
            stderr=subprocess.DEVNULL,
            timeout=10,
        ).decode("utf-8", errors="replace").strip()
        if output:
            parts = [p.strip() for p in output.split("\n")[0].split(",")]
            if len(parts) >= 3:
                result["gpu_available"] = True
                result["gpu_name"] = parts[0]
                result["vram_mb"] = int(float(parts[1]))
                result["cuda_driver"] = parts[2]
    except (FileNotFoundError, subprocess.TimeoutExpired,
            subprocess.CalledProcessError, ValueError, IndexError):
        pass
    return result


def print_hw_summary(os_info, gpu_info):
    """印出硬體偵測摘要。"""
    print(f"  OS      : {os_info['system']} {os_info['release']} ({os_info['machine']})")
    if gpu_info["gpu_available"]:
        print(f"  GPU     : {gpu_info['gpu_name']} ({gpu_info['vram_mb']} MB VRAM)")
        print(f"  CUDA drv: {gpu_info['cuda_driver']}")
    else:
        print("  GPU     : 未偵測到 NVIDIA GPU")


# ============================================================
# 0.5 environment.yml 動態產生（Core + Optional groups）
# ============================================================

_ENV_HEADER = """\
# Auto-generated by init.py
# groups: {groups}
# 重新產生：python init.py [--with <group>...] [--force-cpu | --force-gpu]
name: ai-office
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - pip:
"""

# 核心通用套件（預設安裝）
_PIP_CORE = """\
    # --- Core: data processing ---
    - openpyxl
    - xlrd
    - chardet
    - pyyaml
    - requests

    # --- Core: document processing ---
    - python-docx
    - python-pptx
    - PyMuPDF
    - pdfplumber

    # --- Core: MCP server ---
    - mcp

    # --- Core: utilities ---
    - python-dotenv
    - pandas

    # --- Core: Windows COM automation ---
    - pywin32; sys_platform == "win32"

    # --- Core: Knowledge base (vector search + workflow FSM) ---
    - sqlite-vec
    - transitions
"""

# 可選套件群組（--with <group> 啟用）
_PIP_OPTIONAL_GROUPS = {
    "ocr": """\
    # --- Group: OCR / PDF vision ---
    - rapidocr
    - docling
""",
    "mes": """\
    # --- Group: MES SSRS + browser automation ---
    - requests-ntlm
    - playwright
""",
    "cad": """\
    # --- Group: AutoCAD DXF + 3D modeling ---
    - ezdxf
    - trimesh
    - shapely
    - matplotlib
    - mapbox-earcut
    - manifold3d
""",
    "oracle": """\
    # --- Group: Oracle DB ---
    - oracledb
""",
    "ml": """\
    # --- Group: Machine learning / statistics ---
    - scikit-learn
    - statsmodels
    - matplotlib
    - lightgbm
    - shap
    - ruptures
    - mlxtend
""",
    "causal": """\
    # --- Group: Causal / Bayesian networks ---
    - pgmpy
""",
    "ai-runtime-gpu": """\
    # --- Group: AI runtime (PyTorch CUDA + ONNX GPU) ---
    - --extra-index-url https://download.pytorch.org/whl/cu128
    - torch
    - torchvision
    - onnxruntime-gpu
""",
    "ai-runtime-cpu": """\
    # --- Group: AI runtime (PyTorch CPU + ONNX CPU) ---
    - --extra-index-url https://download.pytorch.org/whl/cpu
    - torch
    - torchvision
    - onnxruntime
""",
}


def resolve_groups(requested, force_cpu=False, force_gpu=False):
    """根據 --with / --force-cpu / --force-gpu 組出最終 groups 清單。

    衝突規則：
    - ai-runtime-gpu 與 ai-runtime-cpu 不得同時啟用
    - --force-cpu 會拒絕 ai-runtime-gpu（並 warn）
    - --force-gpu 會拒絕 ai-runtime-cpu（並 warn）
    """
    groups = []
    seen = set()
    for g in requested or []:
        if g not in _PIP_OPTIONAL_GROUPS:
            print(f"  [ERROR] 未知 group: '{g}'（可用：{', '.join(_PIP_OPTIONAL_GROUPS)}）")
            sys.exit(2)
        if g in seen:
            continue
        seen.add(g)
        groups.append(g)

    if "ai-runtime-gpu" in seen and "ai-runtime-cpu" in seen:
        print("  [ERROR] ai-runtime-gpu 與 ai-runtime-cpu 不可同時啟用")
        sys.exit(2)

    if force_cpu and "ai-runtime-gpu" in seen:
        print("  [WARN] --force-cpu 與 ai-runtime-gpu 衝突，移除 ai-runtime-gpu")
        groups = [g for g in groups if g != "ai-runtime-gpu"]
    if force_gpu and "ai-runtime-cpu" in seen:
        print("  [WARN] --force-gpu 與 ai-runtime-cpu 衝突，移除 ai-runtime-cpu")
        groups = [g for g in groups if g != "ai-runtime-cpu"]

    return groups


def generate_environment_yml(groups):
    """產生 environment.yml 內容。groups 是已解析的 optional group 清單。"""
    groups_label = ", ".join(groups) if groups else "core-only"
    header = _ENV_HEADER.format(groups=groups_label)
    body = _PIP_CORE
    for g in groups:
        body += _PIP_OPTIONAL_GROUPS[g]
    return header + body


def write_environment_yml(groups, force=False):
    """寫入 environment.yml。groups 不同時會覆寫。"""
    env_path = ROOT / "environment.yml"
    new_content = generate_environment_yml(groups)
    groups_label = ", ".join(groups) if groups else "core-only"

    if env_path.exists() and not force:
        existing = env_path.read_text(encoding="utf-8")
        if f"groups: {groups_label}" in existing:
            print(f"  [SKIP] environment.yml 已是 groups: {groups_label}")
            return False
        print(f"  [UPDATE] environment.yml → groups: {groups_label}")
    else:
        print(f"  [CREATE] environment.yml (groups: {groups_label})")

    env_path.write_text(new_content, encoding="utf-8")
    return True


# ============================================================
# 1. 目錄結構定義
# ============================================================

DIRS = [
    # Kit metadata
    ".aok",

    # 知識庫
    "shared/kb/dynamic/cases",
    "shared/kb/dynamic/patterns",
    "shared/kb/external/standards",
    "shared/kb/external/materials",
    "shared/kb/memory",
    "shared/kb/knowledge_graph",
    "shared/kb/ops_log",

    # Skills（空殼，由使用者/Claude 填入領域知識）
    ".claude/skills",
    ".claude/skills-on-demand",
    ".claude/agent-memory",

    # 專案範本
    "projects/_template/vault/originals",
    "projects/_template/vault/outputs",
    "projects/_template/workspace/db",
    "projects/_template/workspace/memos",
    "projects/_template/workspace/scripts/_deprecated",
]


# ============================================================
# 2. 模板檔案定義（路徑 → 內容）
# ============================================================

TEMPLATES = {}

# --- .env ---
TEMPLATES[".env"] = """\
# AI Office Assistant - Local Environment (DO NOT COMMIT)
# 從 .env.example 複製後填入實際值

# MASTER_API_KEY=
"""

# --- .mcp.json ---
# COM-based MCP servers (xlsx/docx/pptx) only work on Windows
# On Linux/macOS, use openpyxl/python-docx/python-pptx directly
if sys.platform == "win32":
    TEMPLATES[".mcp.json"] = """\
{
  "mcpServers": {
    "pptx": {
      "command": "python",
      "args": ["__ROOT__/shared/tools/mcp_pptx_server.py"]
    },
    "xlsx": {
      "command": "python",
      "args": ["__ROOT__/shared/tools/mcp_xlsx_server.py"]
    },
    "docx": {
      "command": "python",
      "args": ["__ROOT__/shared/tools/mcp_docx_server.py"]
    }
  }
}
"""
else:
    TEMPLATES[".mcp.json"] = """\
{
  "mcpServers": {}
}
"""

# --- shared/kb 骨架 ---
TEMPLATES["shared/kb/dynamic/learning_notes.md"] = """\
# 學習筆記

> 由 kb.py add-learning 寫入。
> 每條必須含 <!-- status: active --> 標記。

<!-- 初始化時建立 -->
"""

TEMPLATES["shared/kb/dynamic/column_semantics.md"] = """\
# 欄位語意定義

> 記錄資料庫欄位的業務含義、值域、注意事項。

<!-- 初始化時建立 -->
"""

TEMPLATES["shared/kb/external/README.md"] = """\
# 外部標準

存放外部標準文件的結構化摘要。
原始 PDF 不入庫，僅存結構化 JSON/MD 摘要。
"""

TEMPLATES["shared/kb/memory/README.md"] = """\
# 中場記憶快照

格式：YYYY-MM-DD.md
觸發條件：≥3 檔案 / DB 變更 / 產出報告 / ≥10 輪對話 / ≥2 決策
"""

TEMPLATES["shared/kb/ops_log/README.md"] = """\
# 操作日誌

記錄資料入庫、批次操作等操作紀錄。
"""

TEMPLATES["shared/kb/knowledge_graph/kb_schema.sql"] = """\
-- Knowledge Graph Index Schema
-- 由 kb.py sync 自動建立，此處為參考

CREATE TABLE IF NOT EXISTS decisions (
    id TEXT PRIMARY KEY,          -- D-001, D-002, ...
    date TEXT,
    project TEXT,
    target TEXT,
    question TEXT,
    decision TEXT,
    impact TEXT,
    status TEXT DEFAULT 'active', -- active | superseded | deprecated
    supersedes TEXT,              -- D-XXX
    refs_skill TEXT,
    refs_db TEXT,
    affects TEXT,
    review_by TEXT,               -- YYYY-MM-DD (TTL)
    source TEXT
);

CREATE TABLE IF NOT EXISTS learnings (
    id TEXT PRIMARY KEY,          -- <prefix>-L01, ...
    title TEXT,
    date TEXT,
    content TEXT,
    confidence TEXT,              -- high | medium | low
    project TEXT,
    related_decision TEXT,
    status TEXT DEFAULT 'active'
);
"""

TEMPLATES[".aok/kit-profile.md"] = """\
# AI-OFFICE Kit Profile

- kit_name: ai-office-kit
- runtime_role: agent-first office assistant
- source_of_truth:
  - shared/kb/knowledge_graph/kb_index.db
  - shared/workflows/definitions/
- startup_contract:
  - read project_state.md
  - load active_rules_summary
  - load open questions
  - generate session_context_bundle
- feedback_contract:
  - post_task updates project_state.md
  - durable decisions/learnings write to DB via kb.py
  - snapshots are retrieval surfaces, not authority
- provider_guidance:
  - AGENTS.md
  - .claude/CLAUDE.md
  - CODEX.template.md
"""

TEMPLATES[".aok/runtime-contracts.md"] = """\
# Runtime Contracts

## Session Start

- Must restore project context from `projects/<PROJECT_ID>/workspace/project_state.md`
- Must load project-scoped active decisions
- Must surface unresolved questions explicitly
- Must generate `.session_context_bundle.md`

## Knowledge Writeback

- Durable decisions/learnings go to `shared/kb/knowledge_graph/kb_index.db`
- Markdown under `shared/kb/` is export / read surface, not authority
- `post_task` must refresh exports when new KB entries were written

## Uncertainty Handling

- Unknown / unresolved / blocked items must be surfaced in project state or workflow outputs
- Session ready status cannot hide open questions behind a clear state
"""

# --- Skill 範本 ---
TEMPLATES[".claude/skills-on-demand/_skill_template/.skill.yaml"] = """\
name: my-skill-name
version: "1.0"
category: analysis          # analysis | testing | coding | reporting
description: "一句話描述此 Skill 的用途"

triggers:
  keywords:
    - "關鍵詞1"
    - "關鍵詞2"
  file_patterns:
    - "*pattern*"
  data_columns: []

requires:
  tools:
    - sqlite3
  knowledge:
    - shared/kb/dynamic/column_semantics.md
  related_skills: []

constraints:
  must_not:
    - "修改原始檔案"
    - "刪除 vault 資料"

rules_count: 0
confidence: low
tested_scenarios: 0
last_updated: "YYYY-MM-DD"
"""

TEMPLATES[".claude/skills-on-demand/_skill_template/SKILL.md"] = """\
---
name: my-skill-name
description: 一句話描述
triggers:
  - 關鍵詞1
  - 關鍵詞2
---

# Skill: my-skill-name

## 規則

### R1: 規則名稱
**描述**：...
**範例**：...

## 參考
- 詳見 references/ 目錄
"""


# ============================================================
# 3. 初始化邏輯
# ============================================================

def create_dirs():
    """建立所有必要目錄。"""
    created = []
    for d in DIRS:
        path = ROOT / d
        if not path.exists():
            path.mkdir(parents=True, exist_ok=True)
            created.append(d)
    return created


def create_templates():
    """建立模板檔案（不覆蓋已存在的）。"""
    created = []
    skipped = []
    for rel_path, content in TEMPLATES.items():
        path = ROOT / rel_path
        if rel_path == ".mcp.json":
            content = content.replace("__ROOT__", str(ROOT).replace("\\", "/"))

        path.parent.mkdir(parents=True, exist_ok=True)

        if path.exists():
            skipped.append(rel_path)
        else:
            path.write_text(content, encoding="utf-8")
            created.append(rel_path)
    return created, skipped


def create_project(name: str):
    """從 _template 建立新專案。"""
    template_dir = ROOT / "projects" / "_template"
    target_dir = ROOT / "projects" / name

    if target_dir.exists():
        print(f"  [SKIP] projects/{name}/ 已存在")
        return False

    if not template_dir.exists():
        print(f"  [ERROR] projects/_template/ 不存在")
        return False

    shutil.copytree(template_dir, target_dir)
    project_md = target_dir / "project.md"
    if project_md.exists():
        text = project_md.read_text(encoding="utf-8")
        text = text.replace("{project-name}", name)
        project_md.write_text(text, encoding="utf-8")

    print(f"  [OK] projects/{name}/ 已從範本建立")
    return True


def init_kb_index():
    """初始化 kb_index.db（若 schema 檔已建立）。"""
    db_path = ROOT / "shared" / "kb" / "knowledge_graph" / "kb_index.db"
    schema_path = ROOT / "shared" / "kb" / "knowledge_graph" / "kb_schema.sql"

    if db_path.exists():
        print("  [SKIP] kb_index.db 已存在")
        return

    if schema_path.exists():
        import sqlite3
        conn = sqlite3.connect(str(db_path))
        conn.executescript(schema_path.read_text(encoding="utf-8"))
        conn.close()
        print("  [OK] kb_index.db 已初始化")
    else:
        print("  [WARN] kb_schema.sql 不存在，跳過 DB 初始化")


def check_conda_env():
    """檢查是否在正確的 conda 環境中。"""
    conda_env = os.environ.get("CONDA_DEFAULT_ENV", "")
    if conda_env == "ai-office":
        print("  [OK] conda env: ai-office")
        return True
    elif conda_env:
        print(f"  [WARN] 目前在 conda env '{conda_env}'，建議切換到 'ai-office'")
        return False
    else:
        print("  [WARN] 未偵測到 conda 環境，建議執行: conda env create -f environment.yml")
        return False


def check_env_file():
    """檢查 .env 是否已設定。"""
    env_path = ROOT / ".env"
    if not env_path.exists():
        print("  [WARN] .env 不存在（已從模板建立空檔）")
        return False

    text = env_path.read_text(encoding="utf-8")
    if "MASTER_API_KEY=" in text and not text.split("MASTER_API_KEY=")[1].strip().startswith("#"):
        api_val = text.split("MASTER_API_KEY=")[1].split("\n")[0].strip()
        if api_val and api_val != "your_api_key_here":
            print("  [OK] .env MASTER_API_KEY 已設定")
            return True

    print("  [WARN] .env 中 MASTER_API_KEY 尚未填入")
    return False


# ============================================================
# 4. Main
# ============================================================

def main():
    parser = argparse.ArgumentParser(
        description="AI Office Assistant 初始化",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="可用 optional groups：" + ", ".join(_PIP_OPTIONAL_GROUPS.keys()),
    )
    parser.add_argument("--project", "-p", help="同時建立一個新專案")
    parser.add_argument(
        "--with", dest="with_groups", action="append", default=[], metavar="GROUP",
        help="啟用 optional group（可重複使用，如 --with ocr --with ml）",
    )
    hw_group = parser.add_mutually_exclusive_group()
    hw_group.add_argument("--force-cpu", action="store_true",
                          help="強制 CPU 模式（拒絕 ai-runtime-gpu）")
    hw_group.add_argument("--force-gpu", action="store_true",
                          help="強制 GPU 模式（拒絕 ai-runtime-cpu）")
    args = parser.parse_args()

    print("=" * 50)
    print("AI Office Assistant — 初始化")
    print("=" * 50)

    # Step 1: 硬體偵測
    print("\n[1/7] 硬體偵測")
    os_info = detect_os_info()
    gpu_info = detect_gpu()
    print_hw_summary(os_info, gpu_info)
    if args.force_cpu:
        print("  (--force-cpu 已指定)")
    elif args.force_gpu:
        print("  (--force-gpu 已指定)")

    # Step 2: 解析 groups + 產生 environment.yml
    print("\n[2/7] 產生 environment.yml")
    groups = resolve_groups(args.with_groups, args.force_cpu, args.force_gpu)
    if groups:
        print(f"  Optional groups: {', '.join(groups)}")
    else:
        print("  Optional groups: (none — core only)")
        if gpu_info["gpu_available"] and not args.force_cpu:
            print("  [TIP] 偵測到 GPU；如需 PyTorch，請加 --with ai-runtime-gpu")
        elif not gpu_info["gpu_available"]:
            print("  [TIP] 未偵測到 GPU；如需 PyTorch CPU 版，請加 --with ai-runtime-cpu")
    env_changed = write_environment_yml(groups)

    # Step 3: Conda 環境檢查
    print("\n[3/7] Conda 環境檢查")
    check_conda_env()
    if env_changed:
        print("  [INFO] environment.yml 已更新，請執行：")
        print("         conda env update -f environment.yml --prune")

    # Step 4: 建立目錄
    print("\n[4/7] 建立目錄結構")
    created_dirs = create_dirs()
    if created_dirs:
        for d in created_dirs:
            print(f"  [OK] {d}/")
    else:
        print("  [SKIP] 所有目錄已存在")

    # Step 5: 建立模板檔案
    print("\n[5/7] 建立模板檔案")
    created_files, skipped_files = create_templates()
    if created_files:
        for f in created_files:
            print(f"  [OK] {f}")
    if skipped_files:
        print(f"  [SKIP] {len(skipped_files)} 個檔案已存在")

    # Step 6: 初始化 KB 索引
    print("\n[6/7] 初始化知識庫索引")
    init_kb_index()

    # Step 7: 環境變數檢查
    print("\n[7/7] 環境變數檢查")
    check_env_file()

    # 可選：建立新專案
    if args.project:
        print(f"\n[+] 建立專案: {args.project}")
        create_project(args.project)

    # 完成摘要
    print("\n" + "=" * 50)
    groups_label = ", ".join(groups) if groups else "core only"
    print(f"初始化完成！(groups: {groups_label})")
    print()
    print("下一步：")
    if env_changed:
        print("  0. conda env update -f environment.yml --prune")
    print("  1. 編輯 .env 填入實際金鑰")
    print("  2. 確認 .mcp.json 路徑正確")
    print("  3. 建立新專案：python init.py --project <name>")
    print()
    print("切換或新增套件群組：")
    print("  python init.py --with <group> [--with <group>...]")
    print(f"  可用 groups：{', '.join(_PIP_OPTIONAL_GROUPS.keys())}")
    print("=" * 50)


if __name__ == "__main__":
    main()
