#!/usr/bin/env python3
"""
db_schema.py — Schema Cache Generator for SQLite databases.

Generates SCHEMA.md alongside .db files so AI agents can read actual
table/column names before writing SQL, preventing "schema hallucination".

Usage:
    python db_schema.py generate <db_path>          # writes SCHEMA.md next to .db
    python db_schema.py generate <db_path> -o <out>  # writes to custom path
    python db_schema.py show <db_path>               # prints schema to stdout
    python db_schema.py validate-sql <db_path> <sql> # checks table/column names

EVO-009: Schema-First SQL Protection
"""
import sqlite3
import sys
import argparse
import re
from pathlib import Path
from datetime import datetime


def get_schema_info(db_path: str) -> dict:
    """Extract full schema information from a SQLite database.

    Returns dict with:
        tables: list of {name, columns: [{name, type, notnull, pk, dflt_value}],
                         row_count, sample_values: {col: [vals]}, indexes: [str]}
        views: list of {name, sql}
    """
    db_path = str(db_path)
    conn = sqlite3.connect(f"file:{db_path}?mode=ro", uri=True)
    conn.row_factory = sqlite3.Row

    result = {"tables": [], "views": [], "db_path": db_path}

    try:
        # Get tables
        tables = conn.execute(
            "SELECT name FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%' ORDER BY name"
        ).fetchall()

        for t in tables:
            tname = t["name"]
            table_info = {
                "name": tname,
                "columns": [],
                "row_count": 0,
                "sample_values": {},
                "indexes": []
            }

            # Column info
            cols = conn.execute(f"PRAGMA table_info([{tname}])").fetchall()
            for c in cols:
                table_info["columns"].append({
                    "name": c["name"],
                    "type": c["type"] or "TEXT",
                    "notnull": bool(c["notnull"]),
                    "pk": bool(c["pk"]),
                    "dflt_value": c["dflt_value"]
                })

            # Row count
            try:
                cnt = conn.execute(f"SELECT COUNT(*) FROM [{tname}]").fetchone()
                table_info["row_count"] = cnt[0] if cnt else 0
            except sqlite3.OperationalError:
                table_info["row_count"] = -1

            # Sample values (top 3 distinct non-null per column, truncated)
            for c in table_info["columns"]:
                cname = c["name"]
                try:
                    samples = conn.execute(
                        f"SELECT DISTINCT [{cname}] FROM [{tname}] "
                        f"WHERE [{cname}] IS NOT NULL LIMIT 3"
                    ).fetchall()
                    vals = []
                    for s in samples:
                        v = s[0]
                        if isinstance(v, str) and len(v) > 60:
                            v = v[:57] + "..."
                        elif isinstance(v, bytes):
                            v = f"<BLOB {len(v)} bytes>"
                        vals.append(str(v))
                    table_info["sample_values"][cname] = vals
                except sqlite3.OperationalError:
                    table_info["sample_values"][cname] = []

            # Indexes
            idxs = conn.execute(
                f"SELECT name, sql FROM sqlite_master WHERE type='index' AND tbl_name=? AND sql IS NOT NULL",
                (tname,)
            ).fetchall()
            table_info["indexes"] = [idx["name"] for idx in idxs]

            result["tables"].append(table_info)

        # Get views
        views = conn.execute(
            "SELECT name, sql FROM sqlite_master WHERE type='view' ORDER BY name"
        ).fetchall()
        for v in views:
            result["views"].append({"name": v["name"], "sql": v["sql"]})

    finally:
        conn.close()

    return result


def format_schema_md(info: dict) -> str:
    """Format schema info as Markdown."""
    lines = []
    db_name = Path(info["db_path"]).name
    now = datetime.now().strftime("%Y-%m-%d %H:%M")

    lines.append(f"# Schema: {db_name}")
    lines.append(f"")
    lines.append(f"> Auto-generated by db_schema.py at {now}")
    lines.append(f"> **Read this file before writing any SQL against this database.**")
    lines.append(f"")

    # Summary table
    lines.append("## Tables Summary")
    lines.append("")
    lines.append("| Table | Columns | Rows |")
    lines.append("|-------|---------|------|")
    for t in info["tables"]:
        lines.append(f"| `{t['name']}` | {len(t['columns'])} | {t['row_count']:,} |")
    lines.append("")

    # Detailed per-table schema
    for t in info["tables"]:
        lines.append(f"## {t['name']}")
        lines.append(f"")
        lines.append(f"**Rows**: {t['row_count']:,}")
        if t["indexes"]:
            lines.append(f"**Indexes**: {', '.join(t['indexes'])}")
        lines.append(f"")
        lines.append("| Column | Type | PK | NotNull | Sample Values |")
        lines.append("|--------|------|----|---------|---------------|")
        for c in t["columns"]:
            pk = "Y" if c["pk"] else ""
            nn = "Y" if c["notnull"] else ""
            samples = t["sample_values"].get(c["name"], [])
            sample_str = ", ".join(f"`{v}`" for v in samples[:3]) if samples else "*empty*"
            lines.append(f"| `{c['name']}` | {c['type']} | {pk} | {nn} | {sample_str} |")
        lines.append("")

    # Views
    if info["views"]:
        lines.append("## Views")
        lines.append("")
        for v in info["views"]:
            lines.append(f"### {v['name']}")
            lines.append(f"```sql")
            lines.append(v["sql"])
            lines.append(f"```")
            lines.append("")

    return "\n".join(lines)


def format_schema_compact(info: dict) -> str:
    """Format schema as compact text for embedding in agent context."""
    lines = []
    for t in info["tables"]:
        cols = ", ".join(c["name"] for c in t["columns"])
        lines.append(f"{t['name']} ({t['row_count']:,} rows): {cols}")
    if info["views"]:
        for v in info["views"]:
            lines.append(f"VIEW {v['name']}")
    return "\n".join(lines)


def validate_sql_names(info: dict, sql: str) -> dict:
    """Check if table and column names in SQL exist in the schema.

    Returns:
        {"valid": bool, "errors": [str], "warnings": [str]}

    Note: This is a best-effort heuristic check, not a full SQL parser.
    It catches the most common hallucination patterns (wrong table/column names)
    but may have false positives with complex CTEs, aliases, or functions.
    """
    result = {"valid": True, "errors": [], "warnings": []}

    # Build lookup sets
    all_tables = {t["name"].lower() for t in info["tables"]}
    all_tables.update(v["name"].lower() for v in info["views"])
    all_columns = {}  # table_lower -> set of col_lower
    all_col_names = set()  # flat set of all column names
    for t in info["tables"]:
        cols = {c["name"].lower() for c in t["columns"]}
        all_columns[t["name"].lower()] = cols
        all_col_names.update(cols)

    # Extract table references (FROM/JOIN clauses)
    # Simple regex - catches most common patterns
    table_refs = re.findall(
        r'(?:FROM|JOIN|INTO|UPDATE|TABLE)\s+\[?(\w+)\]?',
        sql, re.IGNORECASE
    )

    for tref in table_refs:
        if tref.lower() not in all_tables:
            result["valid"] = False
            result["errors"].append(
                f"Table '{tref}' does not exist. "
                f"Available: {', '.join(sorted(t['name'] for t in info['tables']))}"
            )

    # Extract column references from SELECT/WHERE/ORDER BY
    # This is heuristic - skip if table validation already failed
    if result["valid"] and len(info["tables"]) == 1:
        # Single-table DB: can validate column names directly
        table = info["tables"][0]
        valid_cols = {c["name"].lower() for c in table["columns"]}

        # Find identifiers that look like column refs (not in quotes, not functions)
        # Skip keywords, numbers, string literals
        sql_clean = re.sub(r"'[^']*'", "", sql)  # remove string literals
        sql_clean = re.sub(r'"[^"]*"', "", sql_clean)  # remove quoted identifiers

        # Look for column-like refs in SELECT/WHERE
        col_refs = re.findall(r'(?:SELECT|WHERE|AND|OR|BY|ON|SET|,)\s+\[?(\w+)\]?', sql_clean, re.IGNORECASE)
        for cref in col_refs:
            cref_lower = cref.lower()
            # Skip SQL keywords and functions
            sql_keywords = {'select', 'from', 'where', 'and', 'or', 'not', 'in', 'like',
                          'between', 'is', 'null', 'as', 'on', 'join', 'left', 'right',
                          'inner', 'outer', 'group', 'order', 'by', 'having', 'limit',
                          'offset', 'union', 'all', 'distinct', 'case', 'when', 'then',
                          'else', 'end', 'asc', 'desc', 'count', 'sum', 'avg', 'min',
                          'max', 'cast', 'coalesce', 'ifnull', 'substr', 'length',
                          'replace', 'trim', 'upper', 'lower', 'date', 'datetime',
                          'true', 'false', 'exists', 'insert', 'update', 'delete', 'into',
                          'values', 'set', 'create', 'drop', 'alter', 'index', 'table',
                          'view', 'trigger', 'begin', 'commit', 'rollback', 'pragma'}
            if cref_lower in sql_keywords:
                continue
            if cref_lower.isdigit():
                continue
            if cref_lower not in valid_cols and cref_lower not in all_tables:
                result["warnings"].append(
                    f"Column '{cref}' may not exist in table '{table['name']}'. "
                    f"Available: {', '.join(sorted(c['name'] for c in table['columns']))}"
                )

    return result


def generate_schema_file(db_path: str, output_path: str = None) -> str:
    """Generate SCHEMA.md for the given database.

    Returns the output file path.
    """
    db_path = Path(db_path).resolve()
    if not db_path.exists():
        raise FileNotFoundError(f"Database not found: {db_path}")

    info = get_schema_info(str(db_path))
    md = format_schema_md(info)

    if output_path:
        out = Path(output_path)
    else:
        # Use DB-name-specific schema file (e.g., bom.db -> SCHEMA_bom.md)
        # This prevents multiple .db files in the same directory from overwriting
        out = db_path.parent / f"SCHEMA_{db_path.stem}.md"

    out.write_text(md, encoding="utf-8")
    return str(out)


def main():
    parser = argparse.ArgumentParser(
        description="SQLite Schema Cache Generator (EVO-009)"
    )
    sub = parser.add_subparsers(dest="command", required=True)

    # generate
    p_gen = sub.add_parser("generate", help="Generate SCHEMA.md for a database")
    p_gen.add_argument("db_path", help="Path to .db file")
    p_gen.add_argument("-o", "--output", help="Output path (default: SCHEMA.md next to .db)")

    # show
    p_show = sub.add_parser("show", help="Print schema to stdout")
    p_show.add_argument("db_path", help="Path to .db file")
    p_show.add_argument("--compact", action="store_true", help="Compact one-line-per-table format")

    # validate-sql
    p_val = sub.add_parser("validate-sql", help="Validate SQL against actual schema")
    p_val.add_argument("db_path", help="Path to .db file")
    p_val.add_argument("sql", help="SQL statement to validate")

    # generate-all
    p_all = sub.add_parser("generate-all", help="Generate SCHEMA.md for all project databases")
    p_all.add_argument("--root", default=str(Path(__file__).resolve().parent.parent.parent),
                       help="Project root (default: auto-detect)")

    args = parser.parse_args()

    if args.command == "generate":
        out = generate_schema_file(args.db_path, args.output)
        print(f"Schema written to: {out}")

    elif args.command == "show":
        info = get_schema_info(args.db_path)
        if args.compact:
            print(format_schema_compact(info))
        else:
            print(format_schema_md(info))

    elif args.command == "validate-sql":
        info = get_schema_info(args.db_path)
        result = validate_sql_names(info, args.sql)
        if result["errors"]:
            for e in result["errors"]:
                print(f"ERROR: {e}")
        if result["warnings"]:
            for w in result["warnings"]:
                print(f"WARNING: {w}")
        if result["valid"] and not result["warnings"]:
            print("OK: All table/column references appear valid.")
        sys.exit(0 if result["valid"] else 1)

    elif args.command == "generate-all":
        root = Path(args.root)
        count = 0
        for db_file in sorted(root.glob("projects/*/workspace/db/*.db")):
            # Skip backup files
            if "backup" in db_file.name.lower():
                continue
            try:
                out = generate_schema_file(str(db_file))
                print(f"  {db_file.name} -> {out}")
                count += 1
            except Exception as e:
                print(f"  ERROR {db_file.name}: {e}", file=sys.stderr)
        # Also handle kb_index.db
        kb_db = root / "shared" / "kb" / "knowledge_graph" / "kb_index.db"
        if kb_db.exists():
            try:
                out = generate_schema_file(str(kb_db))
                print(f"  kb_index.db -> {out}")
                count += 1
            except Exception as e:
                print(f"  ERROR kb_index.db: {e}", file=sys.stderr)
        print(f"\nGenerated {count} SCHEMA.md files.")


if __name__ == "__main__":
    main()
